import { FeedSource } from '../src/types';

export const RELIABLE_SOURCES: FeedSource[] = [
  // --- GLOBAL NEWS WIRES & AGENCIES (REUTERS, AFP, AP, BLOOMBERG) ---
  {
    id: 'reuters-world',
    name: 'Reuters World Wire',
    url: 'https://news.google.com/rss/search?q=source:Reuters&hl=en-US&gl=US&ceid=US:en',
    category: 'World',
    homepage: 'https://www.reuters.com',
    reliabilityScore: 98,
    bias: 'Center',
    country: 'Global / UK',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'afp-wire',
    name: 'Agence France-Presse (AFP)',
    url: 'https://news.google.com/rss/search?q=source:%22Agence+France-Presse%22+OR+source:%22AFP%22&hl=en-US&gl=US&ceid=US:en',
    category: 'World',
    homepage: 'https://www.afp.com',
    reliabilityScore: 97,
    bias: 'Center',
    country: 'France / Global',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'ap-news-wire',
    name: 'Associated Press (AP)',
    url: 'https://news.google.com/rss/search?q=source:%22Associated+Press%22&hl=en-US&gl=US&ceid=US:en',
    category: 'World',
    homepage: 'https://apnews.com',
    reliabilityScore: 98,
    bias: 'Center',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'bloomberg-markets',
    name: 'Bloomberg Markets Wire',
    url: 'https://news.google.com/rss/search?q=source:Bloomberg+markets+finance&hl=en-US&gl=US&ceid=US:en',
    category: 'Finance',
    homepage: 'https://www.bloomberg.com',
    reliabilityScore: 96,
    bias: 'Center',
    country: 'United States / Global',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'bloomberg-energy',
    name: 'Bloomberg Energy & Commodities',
    url: 'https://news.google.com/rss/search?q=source:Bloomberg+oil+energy+commodities&hl=en-US&gl=US&ceid=US:en',
    category: 'Oil & Energy',
    homepage: 'https://www.bloomberg.com/energy',
    reliabilityScore: 96,
    bias: 'Center',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },

  // --- LEADING GLOBAL NEWSPAPERS (NYT, WSJ, WASHINGTON POST, GUARDIAN) ---
  {
    id: 'nyt-world',
    name: 'The New York Times World',
    url: 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml',
    category: 'World',
    homepage: 'https://www.nytimes.com/section/world',
    reliabilityScore: 95,
    bias: 'Center-Left',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'nyt-business',
    name: 'The New York Times Business',
    url: 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml',
    category: 'Business',
    homepage: 'https://www.nytimes.com/section/business',
    reliabilityScore: 95,
    bias: 'Center-Left',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'wsj-markets',
    name: 'The Wall Street Journal Markets',
    url: 'https://feeds.a.dj.com/rss/RSSMarketsMain.xml',
    category: 'Finance',
    homepage: 'https://www.wsj.com/news/markets',
    reliabilityScore: 95,
    bias: 'Center-Right',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'wsj-world',
    name: 'The Wall Street Journal World',
    url: 'https://feeds.a.dj.com/rss/RSSWorldNews.xml',
    category: 'World',
    homepage: 'https://www.wsj.com/news/world',
    reliabilityScore: 95,
    bias: 'Center-Right',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'wsj-business',
    name: 'The Wall Street Journal Business',
    url: 'https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml',
    category: 'Business',
    homepage: 'https://www.wsj.com/news/business',
    reliabilityScore: 95,
    bias: 'Center-Right',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'washpost-world',
    name: 'The Washington Post World',
    url: 'https://feeds.washingtonpost.com/rss/world',
    category: 'World',
    homepage: 'https://www.washingtonpost.com/world',
    reliabilityScore: 94,
    bias: 'Center-Left',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'washpost-business',
    name: 'The Washington Post Business',
    url: 'https://feeds.washingtonpost.com/rss/business',
    category: 'Business',
    homepage: 'https://www.washingtonpost.com/business',
    reliabilityScore: 94,
    bias: 'Center-Left',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },

  // --- PAKISTAN & REGIONAL (APP, DAWN, TRIBUNE, THE NEWS, GEO) ---
  {
    id: 'app-pakistan',
    name: 'Associated Press of Pakistan (APP)',
    url: 'https://news.google.com/rss/search?q=site:app.com.pk&hl=en-PK&gl=PK&ceid=PK:en',
    category: 'Pakistan',
    homepage: 'https://www.app.com.pk',
    reliabilityScore: 95,
    bias: 'Center',
    country: 'Pakistan',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'dawn-news',
    name: 'Dawn News',
    url: 'https://news.google.com/rss/search?q=site:dawn.com&hl=en-PK&gl=PK&ceid=PK:en',
    category: 'Pakistan',
    homepage: 'https://www.dawn.com',
    reliabilityScore: 93,
    bias: 'Center',
    country: 'Pakistan',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'express-tribune',
    name: 'The Express Tribune',
    url: 'https://tribune.com.pk/feed/latest',
    category: 'Pakistan',
    homepage: 'https://tribune.com.pk',
    reliabilityScore: 91,
    bias: 'Center',
    country: 'Pakistan',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'the-news-pk',
    name: 'The News International',
    url: 'https://news.google.com/rss/search?q=site:thenews.com.pk&hl=en-PK&gl=PK&ceid=PK:en',
    category: 'Pakistan',
    homepage: 'https://www.thenews.com.pk',
    reliabilityScore: 90,
    bias: 'Center',
    country: 'Pakistan',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'geo-news',
    name: 'Geo News English',
    url: 'https://www.geo.tv/rss/1/1',
    category: 'Pakistan',
    homepage: 'https://www.geo.tv',
    reliabilityScore: 89,
    bias: 'Center',
    country: 'Pakistan',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'google-news-pakistan',
    name: 'Pakistan National News Wire',
    url: 'https://news.google.com/rss/search?q=Pakistan+news+when:2d&hl=en-PK&gl=PK&ceid=PK:en',
    category: 'Pakistan',
    homepage: 'https://news.google.com',
    reliabilityScore: 92,
    bias: 'Center',
    country: 'Pakistan',
    status: 'active',
    articlesCount: 0,
  },

  // --- BROADCAST & GLOBAL CORRESPONDENTS ---
  {
    id: 'bbc-world',
    name: 'BBC News',
    url: 'http://feeds.bbci.co.uk/news/world/rss.xml',
    category: 'World',
    homepage: 'https://www.bbc.com/news/world',
    reliabilityScore: 94,
    bias: 'Center',
    country: 'United Kingdom',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'npr-news',
    name: 'NPR News',
    url: 'https://feeds.npr.org/1001/rss.xml',
    category: 'World',
    homepage: 'https://www.npr.org',
    reliabilityScore: 92,
    bias: 'Center',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'the-guardian-world',
    name: 'The Guardian',
    url: 'https://www.theguardian.com/world/rss',
    category: 'World',
    homepage: 'https://www.theguardian.com/world',
    reliabilityScore: 89,
    bias: 'Center-Left',
    country: 'United Kingdom',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'aljazeera-world',
    name: 'Al Jazeera World',
    url: 'https://www.aljazeera.com/xml/rss/all.xml',
    category: 'Conflict Zones',
    homepage: 'https://www.aljazeera.com',
    reliabilityScore: 88,
    bias: 'Center',
    country: 'Qatar / Global',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'un-news',
    name: 'UN News Bureau',
    url: 'https://news.un.org/feed/subscribe/en/news/all/rss.xml',
    category: 'Conflict Zones',
    homepage: 'https://news.un.org',
    reliabilityScore: 97,
    bias: 'Center',
    country: 'United Nations',
    status: 'active',
    articlesCount: 0,
  },

  // --- BUSINESS, MARKETS & COMMODITIES ---
  {
    id: 'cnbc-business',
    name: 'CNBC Business',
    url: 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10001147',
    category: 'Business',
    homepage: 'https://www.cnbc.com/business',
    reliabilityScore: 91,
    bias: 'Center',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'marketwatch-business',
    name: 'MarketWatch Top Stories',
    url: 'https://feeds.content.dowjones.io/public/rss/mw_topstories',
    category: 'Business',
    homepage: 'https://www.marketwatch.com',
    reliabilityScore: 89,
    bias: 'Center-Right',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'cnbc-finance',
    name: 'CNBC Finance',
    url: 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000664',
    category: 'Finance',
    homepage: 'https://www.cnbc.com/finance',
    reliabilityScore: 92,
    bias: 'Center',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'cnbc-energy',
    name: 'CNBC Energy & Oil',
    url: 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=19836768',
    category: 'Oil & Energy',
    homepage: 'https://www.cnbc.com/energy',
    reliabilityScore: 91,
    bias: 'Center',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'oilprice-news',
    name: 'OilPrice.com Energy Wire',
    url: 'https://oilprice.com/rss/main',
    category: 'Oil & Energy',
    homepage: 'https://oilprice.com',
    reliabilityScore: 88,
    bias: 'Tech-Focused',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'marketwatch-commodities',
    name: 'MarketWatch Metals & Gold',
    url: 'https://feeds.content.dowjones.io/public/rss/mw_realtimeheadlines',
    category: 'Gold & Commodities',
    homepage: 'https://www.marketwatch.com/investing/commodities',
    reliabilityScore: 90,
    bias: 'Center-Right',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },

  // --- SPORTS & TECHNOLOGY ---
  {
    id: 'bbc-cricket',
    name: 'BBC Sport Cricket',
    url: 'http://feeds.bbci.co.uk/sport/cricket/rss.xml',
    category: 'Cricket',
    homepage: 'https://www.bbc.com/sport/cricket',
    reliabilityScore: 94,
    bias: 'Center',
    country: 'United Kingdom',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'cricinfo-news',
    name: 'ESPN Cricinfo Wire',
    url: 'https://www.espncricinfo.com/rss/content/story/feeds/0.xml',
    category: 'Cricket',
    homepage: 'https://www.espncricinfo.com',
    reliabilityScore: 93,
    bias: 'Center',
    country: 'Global',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'bbc-football',
    name: 'BBC Sport Football',
    url: 'http://feeds.bbci.co.uk/sport/football/rss.xml',
    category: 'Football',
    homepage: 'https://www.bbc.com/sport/football',
    reliabilityScore: 95,
    bias: 'Center',
    country: 'United Kingdom',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'guardian-football',
    name: 'The Guardian Football',
    url: 'https://www.theguardian.com/football/rss',
    category: 'Football',
    homepage: 'https://www.theguardian.com/football',
    reliabilityScore: 92,
    bias: 'Center-Left',
    country: 'United Kingdom',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'techcrunch',
    name: 'TechCrunch',
    url: 'https://techcrunch.com/feed/',
    category: 'Technology',
    homepage: 'https://techcrunch.com',
    reliabilityScore: 90,
    bias: 'Tech-Focused',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'ars-technica',
    name: 'Ars Technica',
    url: 'https://feeds.arstechnica.com/arstechnica/index',
    category: 'Technology',
    homepage: 'https://arstechnica.com',
    reliabilityScore: 93,
    bias: 'Tech-Focused',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'phys-org',
    name: 'Phys.org',
    url: 'https://phys.org/rss-feed/',
    category: 'Science',
    homepage: 'https://phys.org',
    reliabilityScore: 95,
    bias: 'Science-Peer',
    country: 'Global',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'medical-news-today',
    name: 'Medical News Today',
    url: 'https://rss.medicalnewstoday.com/featurednews.xml',
    category: 'Health',
    homepage: 'https://www.medicalnewstoday.com',
    reliabilityScore: 92,
    bias: 'Science-Peer',
    country: 'United Kingdom',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'nature-news',
    name: 'Nature Journal',
    url: 'https://www.nature.com/nature.rss',
    category: 'Climate',
    homepage: 'https://www.nature.com',
    reliabilityScore: 98,
    bias: 'Science-Peer',
    country: 'Global',
    status: 'active',
    articlesCount: 0,
  },

  // --- OPINION & EDITORIAL (DAWN, THE NEWS, EXPRESS TRIBUNE, WAPO, GUARDIAN, NYT, WSJ, BLOOMBERG, FT, PROJECT SYNDICATE, FOREIGN AFFAIRS) ---
  {
    id: 'dawn-opinion',
    name: 'Dawn Editorial & Opinion',
    url: 'https://news.google.com/rss/search?q=site:dawn.com+opinion+OR+editorial&hl=en-PK&gl=PK&ceid=PK:en',
    category: 'Opinion',
    homepage: 'https://www.dawn.com/opinion',
    reliabilityScore: 94,
    bias: 'Center-Left',
    country: 'Pakistan',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'the-news-opinion',
    name: 'The News International Opinion',
    url: 'https://news.google.com/rss/search?q=site:thenews.com.pk+opinion+OR+editorial&hl=en-PK&gl=PK&ceid=PK:en',
    category: 'Opinion',
    homepage: 'https://www.thenews.com.pk/opinion',
    reliabilityScore: 92,
    bias: 'Center-Right',
    country: 'Pakistan',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'tribune-opinion',
    name: 'The Express Tribune Opinion',
    url: 'https://tribune.com.pk/feed/opinion',
    category: 'Opinion',
    homepage: 'https://tribune.com.pk/opinion',
    reliabilityScore: 91,
    bias: 'Center',
    country: 'Pakistan',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'wapo-opinions',
    name: 'The Washington Post Opinions',
    url: 'https://news.google.com/rss/search?q=site:washingtonpost.com/opinions&hl=en-US&gl=US&ceid=US:en',
    category: 'Opinion',
    homepage: 'https://www.washingtonpost.com/opinions',
    reliabilityScore: 94,
    bias: 'Center-Left',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'guardian-opinion',
    name: 'The Guardian Comment is Free',
    url: 'https://www.theguardian.com/commentisfree/rss',
    category: 'Opinion',
    homepage: 'https://www.theguardian.com/commentisfree',
    reliabilityScore: 93,
    bias: 'Center-Left',
    country: 'United Kingdom',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'nyt-opinion',
    name: 'The New York Times Opinion',
    url: 'https://rss.nytimes.com/services/xml/rss/nyt/Opinion.xml',
    category: 'Opinion',
    homepage: 'https://www.nytimes.com/section/opinion',
    reliabilityScore: 95,
    bias: 'Center-Left',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'wsj-opinion',
    name: 'The Wall Street Journal Opinion',
    url: 'https://news.google.com/rss/search?q=source:%22The+Wall+Street+Journal%22+opinion&hl=en-US&gl=US&ceid=US:en',
    category: 'Opinion',
    homepage: 'https://www.wsj.com/news/opinion',
    reliabilityScore: 95,
    bias: 'Center-Right',
    country: 'United States',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'bloomberg-opinion',
    name: 'Bloomberg Opinion',
    url: 'https://news.google.com/rss/search?q=site:bloomberg.com/opinion&hl=en-US&gl=US&ceid=US:en',
    category: 'Opinion',
    homepage: 'https://www.bloomberg.com/opinion',
    reliabilityScore: 95,
    bias: 'Center',
    country: 'United States / Global',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'project-syndicate-opinion',
    name: 'Project Syndicate',
    url: 'https://www.project-syndicate.org/rss',
    category: 'Opinion',
    homepage: 'https://www.project-syndicate.org',
    reliabilityScore: 96,
    bias: 'Center',
    country: 'Global',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'ft-opinion',
    name: 'Financial Times Opinion',
    url: 'https://news.google.com/rss/search?q=site:ft.com/opinion&hl=en-GB&gl=GB&ceid=GB:en',
    category: 'Opinion',
    homepage: 'https://www.ft.com/opinion',
    reliabilityScore: 96,
    bias: 'Center',
    country: 'United Kingdom / Global',
    status: 'active',
    articlesCount: 0,
  },
  {
    id: 'foreign-affairs-opinion',
    name: 'Foreign Affairs Essays',
    url: 'https://news.google.com/rss/search?q=source:%22Foreign+Affairs%22&hl=en-US&gl=US&ceid=US:en',
    category: 'Opinion',
    homepage: 'https://www.foreignaffairs.com',
    reliabilityScore: 96,
    bias: 'Center',
    country: 'United States / Global',
    status: 'active',
    articlesCount: 0,
  },
];

// Fallback seed curated news with multi-source coverage & genuine photojournalism
export const INITIAL_CURATED_ARTICLES = [
  // --- PAKISTAN (APP, DAWN, TRIBUNE, REUTERS) ---
  {
    originalHeadline: 'Pakistan Tech & IT Exports Cross Record $3.5B Milestone Amid Global Digital Services Demand',
    snippet: 'Pakistan\'s information technology and software services sector registered historic double-digit growth, driven by AI systems engineering, fintech integrations, and cloud consulting across North America, Europe, and GCC markets.',
    category: 'Pakistan' as const,
    sourceName: 'Associated Press of Pakistan (APP)',
    sourceId: 'app-pakistan',
    articleUrl: 'https://www.app.com.pk/national/it-exports-reach-record-highs-pakistan/',
    publishedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    author: 'APP Diplomatic & IT Desk',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'Dawn News',
        sourceId: 'dawn-news',
        articleUrl: 'https://www.dawn.com/news/1829401/it-exports-reach-record-highs',
        articleTitle: 'Dawn Business: Software and Services Exports Surge 24% Year-on-Year',
        publishedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
        author: 'Economic Bureau Islamabad',
      },
      {
        sourceName: 'Reuters World Wire',
        sourceId: 'reuters-world',
        articleUrl: 'https://www.reuters.com/technology/pakistan-tech-exports-record-pace-2026',
        articleTitle: 'Reuters: South Asian Tech Hubs See Growth as Pakistan Software Inflows Surge',
        publishedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        author: 'Asif Shahzad',
      },
      {
        sourceName: 'The Express Tribune',
        sourceId: 'express-tribune',
        articleUrl: 'https://tribune.com.pk/story/2489012/pakistan-software-exports-surge-in-global-markets',
        articleTitle: 'Pakistani Tech Firms Expand Global Footprint as Software Revenue Surges 28%',
        publishedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
        author: 'Salman Siddiqui',
      }
    ]
  },
  {
    originalHeadline: 'State Bank of Pakistan Foreign Exchange Reserves Strengthen as Current Account Balances',
    snippet: 'Foreign exchange liquidity held by the central bank climbed to a 30-month high following robust overseas worker remittances, improved trade terms, and multilateral developmental investments.',
    category: 'Pakistan' as const,
    sourceName: 'The Express Tribune',
    sourceId: 'express-tribune',
    articleUrl: 'https://tribune.com.pk/story/2489055/sbp-forex-reserves-climb-to-multi-year-high',
    publishedAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    author: 'Farooq Baloch',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'Associated Press of Pakistan (APP)',
        sourceId: 'app-pakistan',
        articleUrl: 'https://www.app.com.pk/business/sbp-reserves-report-q3-2026/',
        articleTitle: 'APP Economic: Central Bank Confirms Significant Forex Inflows and Remittance Strength',
        publishedAt: new Date(Date.now() - 16 * 60 * 1000).toISOString(),
        author: 'APP Financial Correspondent',
      },
      {
        sourceName: 'Bloomberg Markets Wire',
        sourceId: 'bloomberg-markets',
        articleUrl: 'https://www.bloomberg.com/news/articles/2026-09-01/pakistan-forex-reserves-rise-to-highest-in-two-years',
        articleTitle: 'Bloomberg: Pakistan Foreign Reserves Bolstered by Strong Diaspora Remittances',
        publishedAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
        author: 'Faseeh Mangi',
      }
    ]
  },

  // --- OIL & ENERGY (REUTERS, BLOOMBERG, WSJ, CNBC) ---
  {
    originalHeadline: 'OPEC+ Extends Voluntary Crude Output Cuts as Global Energy Demand Surges in Q3',
    snippet: 'Major oil-producing nations have agreed to maintain production curbs of 2.2 million barrels per day through late autumn, citing refining capacity rebalancing and shipping security along maritime chokepoints.',
    category: 'Oil & Energy' as const,
    sourceName: 'Reuters World Wire',
    sourceId: 'reuters-world',
    articleUrl: 'https://www.reuters.com/business/energy/opec-extends-crude-curbs-2026',
    publishedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    author: 'Alex Lawler & Ahmad Ghaddar',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'Bloomberg Energy & Commodities',
        sourceId: 'bloomberg-energy',
        articleUrl: 'https://www.bloomberg.com/news/articles/2026-09-01/opec-plus-agrees-to-extend-supply-cuts-amid-firm-brent-prices',
        articleTitle: 'Bloomberg: OPEC+ Ministers Reaffirm Tight Market Stance as Brent Holds Above $90',
        publishedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
        author: 'Grant Smith & Salma El Wardany',
      },
      {
        sourceName: 'The Wall Street Journal Markets',
        sourceId: 'wsj-markets',
        articleUrl: 'https://www.wsj.com/articles/oil-prices-rise-as-opec-nations-maintain-output-discipline-11693500000',
        articleTitle: 'WSJ: Oil Climbs After Producers Signal Continued Supply Restraints',
        publishedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
        author: 'Benoit Faucon',
      },
      {
        sourceName: 'CNBC Energy & Oil',
        sourceId: 'cnbc-energy',
        articleUrl: 'https://www.cnbc.com/energy/opec-output-cuts-crude-surge-2026',
        articleTitle: 'CNBC: Brent Crude Climbs Higher as Energy Traders Digest OPEC+ Quota Agreement',
        publishedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
        author: 'Natasha Turak',
      }
    ]
  },

  // --- GOLD & COMMODITIES (REUTERS, BLOOMBERG, WSJ, FT) ---
  {
    originalHeadline: 'Gold Hits Historic Highs Above $2,650/oz as Global Central Banks Expand Bullion Reserves',
    snippet: 'Spot gold prices broke past key resistance levels this morning following substantial reserve accumulations by sovereign monetary authorities seeking hedge assets amidst sovereign debt recalibrations.',
    category: 'Gold & Commodities' as const,
    sourceName: 'The Wall Street Journal Markets',
    sourceId: 'wsj-markets',
    articleUrl: 'https://www.wsj.com/finance/commodities-futures/gold-prices-notch-new-record-high-on-central-bank-buying-11693500000',
    publishedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    author: 'Hardika Singh',
    imageUrl: 'https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'Reuters World Wire',
        sourceId: 'reuters-world',
        articleUrl: 'https://www.reuters.com/markets/commodities/gold-surges-all-time-high-safe-haven-inflows-2026',
        articleTitle: 'Reuters: Precious Metals Rally as Spot Gold Touches Fresh All-Time Peak',
        publishedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
        author: 'Brijesh Patel',
      },
      {
        sourceName: 'Bloomberg Markets Wire',
        sourceId: 'bloomberg-markets',
        articleUrl: 'https://www.bloomberg.com/news/articles/2026-09-01/gold-extends-record-breaking-run-on-sovereign-purchases',
        articleTitle: 'Bloomberg: Bullion Demand Accelerates as Sovereign Wealth Funds Rebalance',
        publishedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
        author: 'Eddie Spence',
      }
    ]
  },

  // --- WORLD & GEOPOLITICS (AFP, REUTERS, NYT, WASHINGTON POST) ---
  {
    originalHeadline: 'UN Security Council Negotiates Humanitarian Corridors and De-escalation Protocol in Eastern Mediterranean Basin',
    snippet: 'Special envoys and regional diplomats have drafted a ceasefire verification framework to protect critical civilian infrastructure, shipping waterways, and international aid logistics hubs.',
    category: 'Conflict Zones' as const,
    sourceName: 'Agence France-Presse (AFP)',
    sourceId: 'afp-wire',
    articleUrl: 'https://www.afp.com/en/news/un-security-council-ceasefire-resolution-drafted',
    publishedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    author: 'AFP Diplomatic Bureau',
    imageUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'The Washington Post World',
        sourceId: 'washpost-world',
        articleUrl: 'https://www.washingtonpost.com/world/2026/09/01/un-diplomats-framework-eastern-mediterranean/',
        articleTitle: 'Washington Post: Envoys Draft International Buffer Protocol at Geneva Summit',
        publishedAt: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
        author: 'John Hudson & Missy Ryan',
      },
      {
        sourceName: 'The New York Times World',
        sourceId: 'nyt-world',
        articleUrl: 'https://www.nytimes.com/2026/09/01/world/middleeast/un-ceasefire-negotiations-aid-corridors.html',
        articleTitle: 'NYT: UN Council Weighs Enforceable Shipping Corridor Safeguards',
        publishedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        author: 'Farnaz Fassihi',
      },
      {
        sourceName: 'Reuters World Wire',
        sourceId: 'reuters-world',
        articleUrl: 'https://www.reuters.com/world/middle-east/un-diplomats-outline-monitoring-mechanism-2026',
        articleTitle: 'Reuters: Envoys Advance Multi-Party Verification Plan for Regional De-escalation',
        publishedAt: new Date(Date.now() - 36 * 60 * 1000).toISOString(),
        author: 'Michelle Nichols',
      }
    ]
  },

  // --- BUSINESS & CORPORATE (NYT, WSJ, BLOOMBERG, REUTERS) ---
  {
    originalHeadline: 'Global Semiconductor Giants Form $65 Billion Foundry Consortium for 1.4nm Silicon Nodes',
    snippet: 'Leading microelectronics manufacturers across North America, Europe, and Asia have unveiled a joint capital expenditure blueprint to construct next-generation extreme ultraviolet (EUV) fabrication facilities.',
    category: 'Business' as const,
    sourceName: 'The Wall Street Journal Business',
    sourceId: 'wsj-business',
    articleUrl: 'https://www.wsj.com/tech/semiconductors-foundry-consortium-next-gen-nodes-11693500000',
    publishedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    author: 'Asa Fitch',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'The New York Times Business',
        sourceId: 'nyt-business',
        articleUrl: 'https://www.nytimes.com/2026/09/01/business/chip-makers-consortium-14nm-foundries.html',
        articleTitle: 'NYT: Global Chipmakers Forge $65B Alliance to Accelerate Advanced Silicon Production',
        publishedAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
        author: 'Don Clark',
      },
      {
        sourceName: 'Bloomberg Markets Wire',
        sourceId: 'bloomberg-markets',
        articleUrl: 'https://www.bloomberg.com/news/articles/2026-09-01/semiconductor-manufacturers-unite-on-65-billion-capex-plan',
        articleTitle: 'Bloomberg: Chip Consortium Announces Strategic Foundry Investments Across 3 Continents',
        publishedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
        author: 'Ian King',
      }
    ]
  },

  // --- FINANCE (BLOOMBERG, WSJ, REUTERS, FT) ---
  {
    originalHeadline: 'Federal Reserve and Central Banks Launch Real-Time Cross-Border FX Settlement Architecture',
    snippet: 'Monetary authorities have completed pilot integration of an ISO-20022 compliant high-speed wholesale liquidity channel, reducing multi-currency foreign exchange clearance from two days to 8 seconds.',
    category: 'Finance' as const,
    sourceName: 'Bloomberg Markets Wire',
    sourceId: 'bloomberg-markets',
    articleUrl: 'https://www.bloomberg.com/news/articles/2026-09-01/central-banks-launch-sub-10-second-fx-settlement-system',
    publishedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    author: 'Craig Torres & Jana Randow',
    imageUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'The Wall Street Journal Markets',
        sourceId: 'wsj-markets',
        articleUrl: 'https://www.wsj.com/economy/central-banking/global-central-banks-test-instant-cross-border-settlement-11693500000',
        articleTitle: 'WSJ: Central Banks Complete Real-Time Foreign Exchange Clearing Architecture',
        publishedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
        author: 'Nick Timiraos',
      },
      {
        sourceName: 'Reuters World Wire',
        sourceId: 'reuters-world',
        articleUrl: 'https://www.reuters.com/business/finance/central-banks-unveil-wholesale-liquidity-corridor-2026',
        articleTitle: 'Reuters: Real-Time Currency Settlement Overhauls International Banking Transfers',
        publishedAt: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
        author: 'Marc Jones',
      }
    ]
  },

  // --- CRICKET ---
  {
    originalHeadline: 'ICC Finalizes World Test Championship Fixtures and Next-Gen Smart Ball Tracking Tech',
    snippet: 'The International Cricket Council has ratified the upcoming championship schedule while rolling out high-frequency micro-sensor cricket balls to eliminate edge and seam bounce ambiguities in Decision Review Systems (DRS).',
    category: 'Cricket' as const,
    sourceName: 'Associated Press of Pakistan (APP)',
    sourceId: 'app-pakistan',
    articleUrl: 'https://www.app.com.pk/sports/icc-announces-wtc-schedule-and-tech-updates/',
    publishedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    author: 'APP Sports Correspondent',
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'BBC Sport Cricket',
        sourceId: 'bbc-cricket',
        articleUrl: 'https://www.bbc.com/sport/cricket/world-test-championship-tech-schedule',
        articleTitle: 'BBC Sport: ICC Ratifies Championship Schedule with Micro-Sensor Tracking Innovations',
        publishedAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
        author: 'Stephan Shemilt',
      },
      {
        sourceName: 'ESPN Cricinfo Wire',
        sourceId: 'cricinfo-news',
        articleUrl: 'https://www.espncricinfo.com/story/icc-confirms-smart-ball-telemetry-for-marquee-series-142890',
        articleTitle: 'Sensors in the Seam: ICC Approves Real-Time Ball Telemetry for Marquee Series',
        publishedAt: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
        author: 'Andrew Miller',
      }
    ]
  },

  // --- FOOTBALL ---
  {
    originalHeadline: 'UEFA Champions League Adopts Automated Offside Laser Tracking for Group Stages',
    snippet: 'European football governing body UEFA has confirmed full deployment of ultra-high frame rate optical mesh systems across all stadium venues, delivering sub-second offside determinations with 3D limb visualization.',
    category: 'Football' as const,
    sourceName: 'Agence France-Presse (AFP)',
    sourceId: 'afp-wire',
    articleUrl: 'https://www.afp.com/en/sports/uefa-champions-league-automated-offside-system',
    publishedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    author: 'AFP Sports Desk Paris',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'The Guardian Football',
        sourceId: 'guardian-football',
        articleUrl: 'https://www.theguardian.com/football/2026/sep/01/uefa-champions-league-automated-offside-tech',
        articleTitle: 'The Guardian: UEFA Implements 3D Limb Tracking to Eliminate Offside Delays',
        publishedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
        author: 'Sid Lowe',
      }
    ]
  },

  // --- TECHNOLOGY ---
  {
    originalHeadline: 'Solid-State Battery Breakthrough Doubles EV Range with 10-Minute Rapid Charge',
    snippet: 'Researchers at national energy laboratories demonstrate a ceramic electrolyte composition that achieves 800-mile range while maintaining stability across 2,000 thermal cycles.',
    category: 'Technology' as const,
    sourceName: 'The New York Times World',
    sourceId: 'nyt-world',
    articleUrl: 'https://www.nytimes.com/2026/09/01/technology/solid-state-battery-commercial-trial.html',
    publishedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    author: 'Jack Ewing',
    imageUrl: 'https://images.unsplash.com/photo-1558441719-8b489c63f7d1?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'Ars Technica',
        sourceId: 'ars-technica',
        articleUrl: 'https://arstechnica.com/science/2026/09/solid-state-battery-breakthrough-ev/',
        articleTitle: 'Ars Technica: Ceramic Electrolyte Breakthrough Unlocks 800-Mile EV Pack',
        publishedAt: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
        author: 'John Timmer',
      },
      {
        sourceName: 'TechCrunch',
        sourceId: 'techcrunch',
        articleUrl: 'https://techcrunch.com/2026/09/01/solid-state-batteries-reach-commercial-milestone/',
        articleTitle: 'TechCrunch: Solid-State Battery Commercialization Moves Into Mass Production Phase',
        publishedAt: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
        author: 'Kirsten Korosec',
      }
    ]
  },

  // --- SCIENCE ---
  {
    originalHeadline: 'James Webb Space Telescope Identifies Atmospheric Biosignature Candidates on Temperate Exoplanet',
    snippet: 'Spectroscopic observations of TRAPPIST-1e reveal persistent atmospheric compounds including methane-ozone disequilibria, providing the strongest chemical anomaly observed beyond our solar system.',
    category: 'Science' as const,
    sourceName: 'The Washington Post World',
    sourceId: 'washpost-world',
    articleUrl: 'https://www.washingtonpost.com/science/2026/09/01/webb-telescope-trappist-atmosphere/',
    publishedAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    author: 'Joel Achenbach',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'Phys.org',
        sourceId: 'phys-org',
        articleUrl: 'https://phys.org/news/2026-09-jwst-biosignatures-trappist.html',
        articleTitle: 'Phys.org: JWST Detects Atmospheric Disequilibrium on Habitable-Zone Exoplanet',
        publishedAt: new Date(Date.now() - 85 * 60 * 1000).toISOString(),
        author: 'Astrophysics Division',
      }
    ]
  },

  // --- CLIMATE ---
  {
    originalHeadline: 'Global Climate Summit Reaches Landmark Accord on $420B Cross-Border Renewable Grids',
    snippet: 'Delegates from 140 nations have ratified an agreement pledging $420 billion towards interconnected renewable electrical grids and next-generation solid-state battery storage by 2030.',
    category: 'Climate' as const,
    sourceName: 'Reuters World Wire',
    sourceId: 'reuters-world',
    articleUrl: 'https://www.reuters.com/sustainability/climate-energy/global-summit-agrees-420b-renewable-grid-deal-2026',
    publishedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    author: 'Valerie Volcovici',
    imageUrl: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'The Guardian',
        sourceId: 'the-guardian-world',
        articleUrl: 'https://www.theguardian.com/environment/2026/sep/01/renewable-grid-pact-signed',
        articleTitle: 'The Guardian: 140 Nations Sign $420bn Interconnected Renewable Grid Treaty',
        publishedAt: new Date(Date.now() - 100 * 60 * 1000).toISOString(),
        author: 'Fiona Harvey',
      }
    ]
  },

  // --- HEALTH ---
  {
    originalHeadline: 'Targeted mRNA Therapeutic Demonstrates 85% Efficacy in Halting Autoimmune Progression',
    snippet: 'Phase 3 clinical trial findings published in the medical press highlight a targeted tolerance-inducing mRNA treatment that suppresses autoimmune attacks without broad immunosuppression.',
    category: 'Health' as const,
    sourceName: 'The New York Times World',
    sourceId: 'nyt-world',
    articleUrl: 'https://www.nytimes.com/2026/09/01/health/mrna-autoimmune-treatment-trial.html',
    publishedAt: new Date(Date.now() - 105 * 60 * 1000).toISOString(),
    author: 'Gina Kolata',
    imageUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'Medical News Today',
        sourceId: 'medical-news-today',
        articleUrl: 'https://www.medicalnewstoday.com/articles/mrna-autoimmune-breakthrough-clinical-trial',
        articleTitle: 'Medical News Today: mRNA Tolerance Therapy Shows Unprecedented Clinical Efficacy',
        publishedAt: new Date(Date.now() - 115 * 60 * 1000).toISOString(),
        author: 'Medical Review Board',
      }
    ]
  },

  // --- OPINION & EDITORIAL (DAWN, THE NEWS, TRIBUNE, WAPO, GUARDIAN, NYT, WSJ, BLOOMBERG, PROJECT SYNDICATE) ---
  {
    originalHeadline: 'Dawn Editorial: Moving Beyond Sovereign Debt Cycles Toward Structural Fiscal Solvency',
    snippet: 'Pakistan cannot afford to treat fiscal consolidation merely as a periodic checklist for multilateral bailout reviews; long-term economic independence requires widening the direct tax net, privatizing bleeding state enterprises, and removing bureaucratic hurdles for exporters.',
    category: 'Opinion' as const,
    sourceName: 'Dawn Editorial & Opinion',
    sourceId: 'dawn-opinion',
    articleUrl: 'https://www.dawn.com/news/1829910/editorial-structural-fiscal-solvency',
    publishedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    author: 'Dawn Editorial Board',
    imageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'The News International Opinion',
        sourceId: 'the-news-opinion',
        articleUrl: 'https://www.thenews.com.pk/print/123456-breaking-the-debt-trap',
        articleTitle: 'The News Op-Ed: Escaping the Balance of Payments Quagmire Through Export Realism',
        publishedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
        author: 'Dr. Ishrat Husain',
      },
      {
        sourceName: 'The Express Tribune Opinion',
        sourceId: 'tribune-opinion',
        articleUrl: 'https://tribune.com.pk/story/2489800/rethinking-tax-broadening-and-provincial-shares',
        articleTitle: 'Tribune Analysis: Why Direct Agricultural and Retail Taxation Is No Longer Optional',
        publishedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
        author: 'Sakib Sherani',
      }
    ]
  },
  {
    originalHeadline: 'Washington Post Editorial: Why Democratic Resilience Demands Independent Press Protections',
    snippet: 'As generative media floods the information commons and coordinated political disinformation campaigns accelerate, constitutional safeguards for independent investigative journalism represent the indispensable cornerstone of democratic self-governance.',
    category: 'Opinion' as const,
    sourceName: 'The Washington Post Opinions',
    sourceId: 'wapo-opinions',
    articleUrl: 'https://www.washingtonpost.com/opinions/2026/09/01/democratic-resilience-press-freedoms/',
    publishedAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    author: 'The Washington Post Editorial Board',
    imageUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'The New York Times Opinion',
        sourceId: 'nyt-opinion',
        articleUrl: 'https://www.nytimes.com/2026/09/01/opinion/press-freedoms-disinformation-age.html',
        articleTitle: 'NYT Guest Essay: Guarding Truth in an Era of Autonomous Propaganda',
        publishedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
        author: 'David French',
      }
    ]
  },
  {
    originalHeadline: 'Wall Street Journal Editorial: Central Banks Must Guard Credibility as Global Inflation Moderates',
    snippet: 'Monetary policy independence is painfully achieved and rapidly squandered. As headline price indices normalize, fiscal authorities must not pressure central bankers into premature easing cycles that reignite cost-of-living volatility.',
    category: 'Opinion' as const,
    sourceName: 'The Wall Street Journal Opinion',
    sourceId: 'wsj-opinion',
    articleUrl: 'https://www.wsj.com/articles/central-bank-credibility-and-rate-discipline-2026',
    publishedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    author: 'WSJ The Editorial Board',
    imageUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'Bloomberg Opinion',
        sourceId: 'bloomberg-opinion',
        articleUrl: 'https://www.bloomberg.com/opinion/articles/2026-09-01/the-fed-must-stay-laser-focused-on-core-metrics',
        articleTitle: 'Bloomberg Column: Central Bankers Must Not Bend to Election-Year Whispers',
        publishedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
        author: 'Mohamed A. El-Erian',
      },
      {
        sourceName: 'Financial Times Opinion',
        sourceId: 'ft-opinion',
        articleUrl: 'https://www.ft.com/content/opinion-central-bank-independence',
        articleTitle: 'FT Editorial: Maintaining the Sanctity of Monetary Anchors in Turbulent Times',
        publishedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
        author: 'Martin Wolf',
      }
    ]
  },
  {
    originalHeadline: 'The Guardian Comment: Climate Justice Requires Direct Loss-and-Damage Funding, Not Voluntary Pledges',
    snippet: 'Vulnerable populations facing catastrophic monsoons and coastal erosion cannot rebuild their livelihoods on unfulfilled summit promises; international climate treaties must operationalize binding capital replenishment from historic polluters.',
    category: 'Opinion' as const,
    sourceName: 'The Guardian Comment is Free',
    sourceId: 'guardian-opinion',
    articleUrl: 'https://www.theguardian.com/commentisfree/2026/sep/01/climate-justice-loss-damage-funding',
    publishedAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    author: 'George Monbiot',
    imageUrl: 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'Project Syndicate',
        sourceId: 'project-syndicate-opinion',
        articleUrl: 'https://www.project-syndicate.org/commentary/climate-reparations-and-vulnerable-economies-2026',
        articleTitle: 'Project Syndicate: The Economic Moral Imperative of Global Loss and Damage Mechanisms',
        publishedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        author: 'Joseph E. Stiglitz',
      }
    ]
  },
  {
    originalHeadline: 'Bloomberg Opinion: The Sovereign Artificial Intelligence Race Is Reshaping Geopolitics',
    snippet: 'Compute capacity, dedicated nuclear micro-grids, and national semiconductor fabrication clusters have become the modern sovereign assets. Nations lacking domestic compute autonomy risk becoming digital vassal states in the decade ahead.',
    category: 'Opinion' as const,
    sourceName: 'Bloomberg Opinion',
    sourceId: 'bloomberg-opinion',
    articleUrl: 'https://www.bloomberg.com/opinion/articles/2026-09-01/sovereign-ai-is-the-new-arms-race',
    publishedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    author: 'Parmy Olson',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'The Washington Post Opinions',
        sourceId: 'wapo-opinions',
        articleUrl: 'https://www.washingtonpost.com/opinions/2026/09/01/national-ai-infrastructure-alliances/',
        articleTitle: 'WaPo Column: Why Computing Infrastructure Is Now Equivalent to Strategic Oil Reserves',
        publishedAt: new Date(Date.now() - 38 * 60 * 1000).toISOString(),
        author: 'David Ignatius',
      }
    ]
  },
  {
    originalHeadline: 'Express Tribune Op-Ed: Unlocking Trans-Regional Commerce Along the South-Central Asian Corridor',
    snippet: 'Connecting Karachi and Gwadar maritime terminals with landlocked Central Asian republics through modern rail and customs harmonisation offers Pakistan its greatest transformative geopolitical dividend in a generation.',
    category: 'Opinion' as const,
    sourceName: 'The Express Tribune Opinion',
    sourceId: 'tribune-opinion',
    articleUrl: 'https://tribune.com.pk/story/2489912/trans-regional-connectivity-and-pakistans-transit-trade',
    publishedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    author: 'Senator Mushahid Hussain Sayed',
    imageUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1200&q=80',
    duplicates: [
      {
        sourceName: 'Dawn Editorial & Opinion',
        sourceId: 'dawn-opinion',
        articleUrl: 'https://www.dawn.com/news/1829988/central-asia-transit-pacts',
        articleTitle: 'Dawn Op-Ed: The Economic Geometry of Eurasian Transit Corridors',
        publishedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
        author: 'Maleeha Lodhi',
      }
    ]
  }
];

